background {
    monitor = eDP-1
    path = $HOME/wallpapers/bg08.jpg
    blur_passes = 0
    blur_size = 7
    noise = 0.0117
    contrast = 0.8916
    brightness = 0.8172
    vibrancy = 0.1696
    vibrancy_darkness = 0.0
}

input-field {
    monitor = eDP-1
    size = 200, 50
    outline_thickness = 2
    rounding = -1
    outer_color = rgba(0, 0, 0, 0.4)   
    inner_color = rgba(0, 0, 0, 0.4)    
    font_color = rgb(200, 200, 200)     
    placeholder_text = <i>Input password...</i>
    hide_input = false
    rounding = -1 
    position = 0, -30
    halign = center
    valign = center

    # Поведение при ошибке
    fail_color = rgba(255, 50, 50, 0.8)  
    fail_text = <i>Wrong password</i>
    fail_transition = 300
    # Точки (звёздочки) при вводе
    dots_size = 0.25
    dots_spacing = 0.2
    dots_center = true
    dots_rounding = -1

    # Дополнительно
    fade_on_empty = true
    fade_timeout = 1000
    capslock_color = rgba(255, 200, 0, 0.6)
}

label {
    monitor = eDP-1
    text = $TIME
    color = rgba(255, 255, 255, 0.9)
    font_size = 72
    font_family = JetBrains Mono
    position = 0, 100
    halign = center
    valign = center
}

