[General]

DisplayServer=x11

HaltCommand=/usr/bin/systemctl poweroff
RebootCommand=/usr/bin/systemctl reboot

[Users]

MinimumUid=1000
MaximumUid=65000


[Wayland]

SessionDir=/usr/local/share/wayland-sessions,/usr/share/wayland-sessions

SessionLogFile=.local/share/sddm/wayland-sessions.log


[X11]

SessionLogFile=.local/share/sddm/xorg-session.log

[Theme]
Current=silent

[General]
InputMethod=qtvirtualkeyboard

[General]
GreeterEnvironment=QML2_IMPORT_PATH=/usr/share/sddm/themes/silent/components/,QT_IM_MODULE=qtvirtualkeyboard

[General]
GreeterEnvironment=QML2_IMPORT_PATH=/usr/share/sddm/themes/silent/components/,QT_IM_MODULE=qtvirtualkeyboard

[General]
GreeterEnvironment=QML2_IMPORT_PATH=/usr/share/sddm/themes/silent/components/,QT_IM_MODULE=qtvirtualkeyboard

[General]
GreeterEnvironment=QML2_IMPORT_PATH=/usr/share/sddm/themes/silent/components/,QT_IM_MODULE=qtvirtualkeyboard
